### ISSUE TITLE
Improvement: Support both lower case and checksum indexer addresses

### ISSUE THREAD

**Issue by fordN** [graphprotocol/allocation-optimizer#26]
**Is your feature request related to a problem? Please describe.**
Currently if the user inputs the indexer address in checksum format (not all lower case) the program will fail with a non-specific error: `ERROR: LoadError: AllocationOpt.UnknownIndexerError()`.  To resolve this issue, for indexers that are actually on the network, the user simply has to lower case the value they input.  The application should handle this for the user, so that the `UnkownIndexerError` truly means that the address is not found on the network.  

**Describe the solution you'd like**
Process the indexer address input: lower casing it and validating that it's a well formed Ethereum address. Any errors that return from this validation should include clear steps to resolve the issue. At the simplest level just lower casing the input would reduce confusion.

**Comment by anirudh2** [comment]
Thanks for the feedback @fordN! We've included this feature in v2.
