### ISSUE TITLE
Improvement request: Continue iterating on docs

### ISSUE THREAD

**Issue by fordN** [graphprotocol/allocation-optimizer#27]
**Is your feature request related to a problem? Please describe.**
The docs give a brief intro into usage of the tool, but leave a lot of information to be found elsewhere in code or CLI helpers by the user.  Some important questions that it would be great to have answered by the docs: 
- what is the optimizer doing under the hood in detail and just generally (optimizing indexing rewards for specific stake amount)? 
- What exactly are all of the input params and how are they used? 
- More specifically: What is grtGas and how is it used by the optimizer? 
- What is τ? how is it used by the optimizer? What are some suggestions for values to use in different situations?
- What exactly are frozenList, pinList, whitelist, and blacklist? Provide some examples of config files that use these. 
- Can we provide some background and description of each command and when they might be used? i.e What exactly id `optimizesummary` and how to read output? 
- What exactly does `actionqueue` do? why would you use it? etc... The docs just say "This command requires a URL to the indexer management server and a URL to make graph network subgraph queries" but don't provide any background or why.

**Describe the solution you'd like**
As alluded to above: Add to the docs to provide background description of each command, description of each parameter and why they would be used in different contexts, description of outputs and how to use them, and potentially include a few examples for illustration of usage. 

**Additional context**
I have some familiarity with the goals and implementation of this tool and it's still a bit tough to parse what all the inputs should be and why to use them.  Let's make it super clear, so we can onboard many more indexers to using it!

**Comment by anirudh2** [comment]
Thanks for the feedback, @fordN! We've kept this issue in mind while working on v2. Could you check out our updated docs and provide any further feedback you might have?

https://graphprotocol.github.io/allocation-optimizer/latest/

**Comment by hopeyen** [comment]
There hasn't been any response in a while so we will close for now. Feel free to open new issues when there is more improvement requests
