### ISSUE TITLE
Improvement: Include some summary info and docs in main README

### ISSUE THREAD

**Issue by fordN** [graphprotocol/allocation-optimizer#28]
**Is your feature request related to a problem? Please describe.**
When landing on the GitHub repo a potential user should be able to get a quick summary of what the tool does, why it's useful, and maybe some simple usage examples.  It's also a good place to put additional documentation such as how to contribute, etc... 

Right now the README doesn't tell me much: 
```
AllocationOpt is a library for optimising how an indexer should allocate its stake in [The Graph Protocol](https://thegraph.com/en/). For details, visit our [documentation](https://graphprotocol.github.io/AllocationOpt.jl/dev)
```

The description raises questions: optimize for what? Is it really a library or also a CLI tool? A user shouldn't have to search elsewhere to find some of this high level information.

**Comment by anirudh2** [comment]
Thanks for your feedback @fordN! We've updated the README on the main branch now. Please let us know if you have any further suggestions!

https://github.com/graphprotocol/allocation-optimizer/blob/main/README.md

**Comment by hopeyen** [comment]
There hasn't been any response in a while so we will close for now. Feel free to open new issues for further improvements
