### ISSUE TITLE
Bug: Increasing size of blacklist leads to questionable report output

### ISSUE THREAD

**Issue by fordN** [graphprotocol/allocation-optimizer#36]
I added 30 subgraph deployments to the blacklist (making it a total of ~45 subgraphs) and with the new, longer list the generated reports contained questionable strategies.

With the longer blacklist I am now consistently getting a single strategy returned with only 1 subgraph being allocated to. The expected profit is very low, so it doesn't appear to be a valid suggestion to only allocate to 1 subgraph.

**Comment by anirudh2** [comment]
Could you post your config file that you used for this experiment?

**Comment by fordN** [comment]
Hmm... I'm unable to reproduce now, so it's possible I was mixing this experiment setup with the `pinnedList` experiment I was running.   

Hold off on this issue for now? I'll comment again here and tag you if I can reproduce again.

**Comment by fordN** [comment]
Hmm... I'm unable to reproduce now, so it's possible I was mixing this experiment setup with the `pinnedList` experiment I was running.   

Closing the issue now to avoid confusion. I'll revive it if I can reproduce again.

**Comment by anirudh2** [comment]
Sounds good!
