### ISSUE TITLE
Bug: pinnedList is acting like whitelist

### ISSUE THREAD

**Issue by fordN** [graphprotocol/allocation-optimizer#38]
## Observed behavior
When I add a `subgraphDeployment` to the `pinnedList` the optimizer only returns 1 suggested strategy and it suggests I only allocate to that pinnedList subgraph. 

## Expected behavior
Subgraph deployments in the pinnedList will always be included in the suggested allocations (though potentially with minimum signal because they have little expected revenue), but the suggested allocations will also likely include other subgraph deployments.

**Comment by anirudh2** [comment]
This should be fixed the latest release - v2.2.1. Feel free to re-open if this problem pops up again.
