### ISSUE TITLE
Support filtering subgraph syncing network in the config

### ISSUE THREAD

**Issue by fordN** [graphprotocol/allocation-optimizer#42]
As an indexer my graph-node is only setup to support subgraphs that sync certain networks; however, the allocation-optimizer does not support filtering subgraphs by the syncing network.  Because of this I end up doing manual work to add unsupported subgraph deployments to the blacklist in order to filter them out of the optimization runs.  
Adding support for specifying the supported networks in the config would save me a lot of time and work when managing allocations.

**Comment by anirudh2** [comment]
Thanks for your suggestion! We'll look into it!

**Comment by anirudh2** [comment]
Done!
